version: '3.8'

services:
  email-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SMTP_EMAIL=your-email@gmail.com
      - SMTP_PASSWORD=your-password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
