apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-deployment
  labels:
    app: email-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: your-dockerhub-username/email-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SMTP_EMAIL
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: email
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: email-service
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
type: Opaque
data:
  email: your-base64-encoded-email
  password: your-base64-encoded-password
